### PR TITLE
[WIP] Speaker information

### LINKED ISSUE #72: Speaker layout
--- This is an issue for Roy ---
Create a standard layout in which speakers will be shown 
- Create page
- Create layout
- Add speakers

### PR DESCRIPTION
**Pull request by martijnjanssen**
Fixes #72

### CODE REVIEW

**Review by martijnjanssen — COMMENTED** [review]
@royklip if you get the image for the first speaker and remove the css that removes the underline in the program we can merge this. The reason I want the underline removed is that it should be clear that the titles are clickable, and not that it is only clear after hovering over them.

**Comment by TimvdLippe** [comment]
Ah crap, this one now has a merge conflict with the `program-change` :sob:

**Review by TimvdLippe — APPROVED** [review]
@martijnjanssen I fixed the trailing slash issue, but we have to revert that when we deploy with Docker (/sigh)

**Comment by TimvdLippe** [comment]
I have also rebased this PR. So once you approve it you can merge it :smile:

**Pull request merged**
