### PR TITLE
Banner

### PR DESCRIPTION
**Pull request by royklip**
- Change banner
- Change background colors
- Change placement of banner

### CODE REVIEW

**Comment by TimvdLippe** [comment]
I have updated some CSS to fix some small issues. First of all on small screens the banner was too wide causing a weird white strip on the right of the screen. Secondly, the coloring was a bit off. I did extract a CSS variable for this, if you dislike the color you can just change it. I found the previous color a bit harsh, but that is my opinion of course :smile:

**Review by TimvdLippe — APPROVED** [review]

**Comment by martijnjanssen** [comment]
Have you seen what happens to the page on mobile view? There seems to be an issue with the separation of the footer. Also, I think the distinction between the footer and the content need to be more obvious when the page is on mobile view, now it is just plain white/white. The current solution with the thick border is not very elegant.

**Comment by martijnjanssen** [comment]
Another issue is the color of some other elements in the toolbar. The button for the drawer-panel is white, the button is not visible right now.

**Comment by martijnjanssen** [comment]
The `margin-top` on the `symposium-map` needs to be removed on the mobile view. Additionally, the banner-image also needs to reside in a `paper-card` or at least be elevated.

**Comment by martijnjanssen** [comment]
Are we going to discard this PR and make a new one based on #52 for these changes?

**Pull request closed without merging**
